name: Manual Birrificio Schedule

on: workflow_dispatch

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Use the version matching your script

    # Step 3: Install required dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Install requests which is used in your script

    # Step 4: Run the script
    - name: Run the Python script
      env:
        EMAIL_ACCOUNT: ${{ secrets.EMAIL_ACCOUNT }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SENDER_TO_MONITOR: ${{ secrets.SENDER_TO_MONITOR }}
        IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
        IPERAL_PDF_LINK: ${{ secrets.IPERAL_PDF_LINK }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: |
        python main.py -b
